### ISSUE TITLE
RMF can not be installed because of the resource server has no response

### ISSUE THREAD

**Issue by qingtian1771** [osrf/ros2multirobotbook#60]
It seems I can not install it bacause the install server is no response.

I want to install is according the link: https://osrf.github.io/ros2multirobotbook/ , it says:

```
Next you will need to setup the source of RMF packages similar to the previous two steps. First authorizing the key:
curl -s http://rmf.servehttp.com/repos.key | sudo apt-key add -

Secondly adding the repository to the apt sources:
sudo sh -c 'echo "deb http://rmf.servehttp.com/ubuntu/main/ `lsb_release -cs` main" > /etc/apt/sources.list.d/rmf.list'

And now we are ready to install. Let's update our packages:
sudo apt-get update
```
And the update has some problems, it cannot access the rmf resource server.
```
tq@tq-sy:~$ sudo apt-get update
Hit:1 http://mirrors.huaweicloud.com/repository/ubuntu focal InRelease
Get:2 http://mirrors.huaweicloud.com/repository/ubuntu focal-updates InRelease [114 kB]
Get:3 http://mirrors.huaweicloud.com/repository/ubuntu focal-backports InRelease [101 kB]                                             
Get:4 http://mirrors.huaweicloud.com/repository/ubuntu focal-security InRelease [109 kB]                                              
Err:5 http://rmf.servehttp.com/ubuntu/main focal InRelease                                                                            
  Connection failed [IP: 158.140.146.108 80]
Hit:6 http://archive.canonical.com/ubuntu focal InRelease                                                                             
Hit:7 http://packages.osrfoundation.org/gazebo/ubuntu-stable focal InRelease                     
Hit:8 http://packages.ros.org/ros2/ubuntu focal InRelease
Fetched 324 kB in 1s (220 kB/s)
Reading package lists... Done
W: Failed to fetch http://rmf.servehttp.com/ubuntu/main/dists/focal/InRelease  Connection failed [IP: 158.140.146.108 80]
W: Some index files failed to download. They have been ignored, or old ones used instead.
```
So when I install, it can not get the resource.
```
tq@tq-sy:~$ sudo apt-get install ros-foxy-ament-cmake-catch2 ros-foxy-building-gazebo-plugins ros-foxy-building-map-msgs ros-foxy-building-map-tools ros-foxy-rmf-cmake-uncrustify ros-foxy-rmf-dispenser-msgs ros-foxy-rmf-door-msgs ros-foxy-rmf-fleet-adapter ros-foxy-rmf-fleet-msgs ros-foxy-rmf-lift-msgs ros-foxy-rmf-task-msgs ros-foxy-rmf-traffic-msgs ros-foxy-rmf-traffic-ros2 ros-foxy-rmf-traffic ros-foxy-rmf-utils ros-foxy-traffic-editor
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package ros-foxy-ament-cmake-catch2
E: Unable to locate package ros-foxy-building-gazebo-plugins
E: Unable to locate package ros-foxy-building-map-msgs
E: Unable to locate package ros-foxy-building-map-tools
E: Unable to locate package ros-foxy-rmf-cmake-uncrustify
E: Unable to locate package ros-foxy-rmf-dispenser-msgs
E: Unable to locate package ros-foxy-rmf-door-msgs
E: Unable to locate package ros-foxy-rmf-fleet-adapter
E: Unable to locate package ros-foxy-rmf-fleet-msgs
E: Unable to locate package ros-foxy-rmf-lift-msgs
E: Unable to locate package ros-foxy-rmf-task-msgs
E: Unable to locate package ros-foxy-rmf-traffic-msgs
E: Unable to locate package ros-foxy-rmf-traffic-ros2
E: Unable to locate package ros-foxy-rmf-traffic
E: Unable to locate package ros-foxy-rmf-utils
E: Unable to locate package ros-foxy-traffic-editor
```
Could any body help me, thanks!

**Comment by marcoag** [comment]
It seems fine from here:

```
$ sudo apt-get update
Get:1 http://rmf.servehttp.com/ubuntu/main focal InRelease [2807 B]
Get:2 http://rmf.servehttp.com/ubuntu/main focal/main amd64 Packages [36.9 kB]
Get:3 http://packages.ros.org/ros2/ubuntu focal InRelease [4670 B]  
..
```

Could you try again?

are you able to `ping rmf.servehttp.com` or access it through the browser?

**Comment by qingtian1771** [comment]
Strange. I cannot ping rmf.servehttp.com, but I can access it through browser.
I still cannot access it through "sudo apt-get update", the same error as before.

**Comment by marcoag** [comment]
Ok, my bad suggesting the ping command as the server has the ping response off. The file your apt is failing to get seems accessible here:

[http://rmf.servehttp.com/ubuntu/main/dists/focal/InRelease](http://rmf.servehttp.com/ubuntu/main/dists/focal/InRelease)

Both, `InRelease` and the `Release` + signature files, seem to be available and accessible:

[http://rmf.servehttp.com/ubuntu/building/dists/focal/](http://rmf.servehttp.com/ubuntu/building/dists/focal/)

can you check if you are able to access this file? I tested from different locations and I can't seem to reproduce your issue...

**Comment by marcoag** [comment]
Since I can't reproduce the issue and there's been a few days of inactivity I will close this issue.

**Comment by dionesiusap** [comment]
Hi, opening this thread again because I got similar issue while following [this tutorial](https://osrf.github.io/ros2multirobotbook/installation.html#setup-sources-and-installation-of-rmf) to install RMF. Seems that it cannot access the `rmf.servehttp.com` server. Trying to access this address from web browser also doesn't work.

Running `curl -s http://rmf.servehttp.com/repos.key | sudo apt-key add -` returns
```
gpg: no valid OpenPGP data found.
```
Likewise, running basic curl to get the key `curl http://rmf.servehttp.com/repos.key` returns
```
curl: (7) Failed to connect to rmf.servehttp.com port 80: Connection refused
```

Therefore `sudo apt update` has error and when running `sudo apt install ...` the packages cannot be found.

Any help will be appreciated, thanks!

**Comment by cuizhongren45** [comment]
Hi, I also meet the problem as you. Have you solve this problem?
I unable ping rmf.servehttp.com in terminal and cannot open rfm.servehttp.com in browser. I donot know if the web site down.

Any help will be appreciated ,thanks!
